name = "a0b_tools"
description = "A0B Tools: Runtime Generator"
website = "https://github.com/godunko/a0b-tools"
version = "0.3.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "GPL-3.0-or-later"

project-files=["gnat/a0b_tools.gpr"]
executables=["a0b-runtime"]
auto-gpr-with=false

tags = ["a0b", "tools", "runtime"]

[configuration]
generate_ada = false
generate_gpr = true
generate_c = false

[environment]
PATH.append = "${CRATE_ROOT}/bin"

[[depends-on]]
a0b_base = "*"
gnat = "*"
gnatcoll = "*"
vss_text = "*"
vss_extra = "*"

[[pins]]
vss_text = { url='https://github.com/AdaCore/vss-text.git' }
vss_extra = { url='https://github.com/AdaCore/vss-extra.git' }
